# Generated by Django 4.2.4 on 2024-06-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('description', models.CharField(choices=[('Reclamo', 'Reclamo'), ('Felicitaciones', 'Felicitaciones')], max_length=15)),
                ('message', models.TextField()),
            ],
        ),
    ]
